### ISSUE TITLE
Unhandled Exception in Client Dist

### ISSUE THREAD

**Issue by FFrozTT** [youhacker55/jarbou3#22]
Failed to execute script 'jarbou3' due to unhandled exception: No module named 'Crypto'
Traceback (most recent call last):
  File "jarbou3.py", line 13, in <module>
ModuleNotFoundError: No module named 'Crypto'

This is on the compiled client executable.  Does one need to manage python module dependencies on the client end?

**Comment by TheNewAttacker64** [comment]
can you please run the installer.bat

**Comment by FFrozTT** [comment]
On the client?
First thing I did on the server was run installer.bat, it was full of errors. Spent about an hour adding all Python dependencies by hand. C&C runs and I can do 'Build' command.  Build creates jarbou3.exe.  I move Jarbou3 to client PC and run it, that's when I get this error (on client): No module named 'Crypto'

When I run installer.bat on the client PC, again it's full of errors, will need another hour or so to get through them all.

I was hoping jarbou3.exe was packed with necessary dependencies, but managing Python modules on every client is a bit cumbersome.

**Comment by TheNewAttacker64** [comment]
please make sure you using python 3.11  by checking py -3 -v

**Comment by FFrozTT** [comment]
The instructions says to use the latest Python so I have 3.12.
